using LPCylinderMES.Api.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace LPCylinderMES.Api.Services;

internal static class WorkCenterDocumentPdfBuilder
{
    static WorkCenterDocumentPdfBuilder()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public static byte[] BuildDocument(
        SalesOrder order,
        int lineId,
        string category,
        string documentNo,
        DateTime generatedUtc,
        string actorEmpNo,
        string? notes)
    {
        var safeNotes = string.IsNullOrWhiteSpace(notes) ? "N/A" : notes.Trim();
        return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(32);
                    page.Size(PageSizes.Letter);
                    page.DefaultTextStyle(x => x.FontSize(11));

                    page.Header()
                        .Column(col =>
                        {
                            col.Item().Text($"{category}").SemiBold().FontSize(18);
                            col.Item().Text($"Document No: {documentNo}").FontSize(12);
                        });

                    page.Content()
                        .PaddingTop(16)
                        .Column(col =>
                        {
                            col.Spacing(8);
                            col.Item().Text($"Sales Order ID: {order.Id}");
                            col.Item().Text($"Sales Order No: {order.SalesOrderNo}");
                            col.Item().Text($"Line ID: {lineId}");
                            col.Item().Text($"Customer ID: {order.CustomerId}");
                            col.Item().Text($"Site ID: {order.SiteId}");
                            col.Item().Text($"Generated UTC: {generatedUtc:O}");
                            col.Item().Text($"Generated By: {actorEmpNo}");
                            col.Item().Text($"Notes: {safeNotes}");
                        });
                });
            })
            .GeneratePdf();
    }
}
