// <auto-generated />
using System;
using LPCylinderMES.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LPCylinderMES.Api.Migrations
{
    [DbContext(typeof(LpcAppsDbContext))]
    [Migration("20260224145958_AddQuantityAsShippedToSalesOrderDetails")]
    partial class AddQuantityAsShippedToSalesOrderDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LPCylinderMES.Api.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("address2");

                    b.Property<string>("AddressName")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address_name");

                    b.Property<string>("City")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("city");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("contact_id");

                    b.Property<string>("Country")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("country");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int?>("DefaultSalesEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("default_sales_employee_id");

                    b.Property<string>("PostalCode")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PK__addresse__3213E83F5AE845D5");

                    b.HasIndex("ContactId");

                    b.HasIndex("CustomerId");

                    b.HasIndex(new[] { "Id" }, "ix_addresses_id");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__colors__3213E83F6681F120");

                    b.HasIndex(new[] { "Name" }, "UQ__colors__72E12F1BE3B3B84F")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "ix_colors_id");

                    b.ToTable("colors", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mobile_phone");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("notes");

                    b.Property<string>("OfficePhone")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("office_phone");

                    b.HasKey("Id")
                        .HasName("PK__contacts__3213E83F7213B03C");

                    b.HasIndex("CustomerId");

                    b.HasIndex(new[] { "Email" }, "UQ__contacts__AB6E616477A655DA")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex(new[] { "Id" }, "ix_contacts_id");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerCode")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customer_code");

                    b.Property<int?>("CustomerParentId")
                        .HasColumnType("int")
                        .HasColumnName("customer_parent_id");

                    b.Property<int?>("DefaultBillToId")
                        .HasColumnType("int")
                        .HasColumnName("default_bill_to_id");

                    b.Property<string>("DefaultGauges")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("default_gauges");

                    b.Property<int?>("DefaultNeedCollars")
                        .HasColumnType("int")
                        .HasColumnName("default_need_collars");

                    b.Property<int?>("DefaultNeedFillers")
                        .HasColumnType("int")
                        .HasColumnName("default_need_fillers");

                    b.Property<int?>("DefaultNeedFootRings")
                        .HasColumnType("int")
                        .HasColumnName("default_need_foot_rings");

                    b.Property<int?>("DefaultOrderContactId")
                        .HasColumnType("int")
                        .HasColumnName("default_order_contact_id");

                    b.Property<int?>("DefaultPaymentTermId")
                        .HasColumnType("int")
                        .HasColumnName("default_payment_term_id");

                    b.Property<int?>("DefaultPickUpId")
                        .HasColumnType("int")
                        .HasColumnName("default_pick_up_id");

                    b.Property<int?>("DefaultReturnBrass")
                        .HasColumnType("int")
                        .HasColumnName("default_return_brass");

                    b.Property<int?>("DefaultReturnScrap")
                        .HasColumnType("int")
                        .HasColumnName("default_return_scrap");

                    b.Property<int?>("DefaultSalesEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("default_sales_employee_id");

                    b.Property<int?>("DefaultShipToId")
                        .HasColumnType("int")
                        .HasColumnName("default_ship_to_id");

                    b.Property<int?>("DefaultShipViaId")
                        .HasColumnType("int")
                        .HasColumnName("default_ship_via_id");

                    b.Property<string>("DefaultValveType")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("default_valve_type");

                    b.Property<string>("Email")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("email");

                    b.Property<int?>("LidColorId")
                        .HasColumnType("int")
                        .HasColumnName("lid_color_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("status");

                    b.Property<int?>("TankColorId")
                        .HasColumnType("int")
                        .HasColumnName("tank_color_id");

                    b.HasKey("Id")
                        .HasName("PK__customer__3213E83F98082B0B");

                    b.HasIndex("CustomerParentId");

                    b.HasIndex("DefaultOrderContactId");

                    b.HasIndex("DefaultPaymentTermId");

                    b.HasIndex("DefaultShipViaId");

                    b.HasIndex("LidColorId");

                    b.HasIndex("TankColorId");

                    b.HasIndex(new[] { "Id" }, "ix_customers_id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.CustomerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int?>("LidColorId")
                        .HasColumnType("int")
                        .HasColumnName("lid_color_id");

                    b.Property<int?>("TankColorId")
                        .HasColumnType("int")
                        .HasColumnName("tank_color_id");

                    b.HasKey("Id")
                        .HasName("PK__customer__3213E83F12A48E3E");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LidColorId");

                    b.HasIndex("TankColorId");

                    b.HasIndex(new[] { "Id" }, "ix_customer_items_id");

                    b.ToTable("customer_items", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemDescription")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("item_description");

                    b.Property<string>("ItemNo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("item_no");

                    b.Property<int?>("ItemSize")
                        .HasColumnType("int")
                        .HasColumnName("item_size");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("item_type");

                    b.Property<string>("ProductLine")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("product_line");

                    b.Property<bool?>("RequiresCollarOption")
                        .HasColumnType("bit")
                        .HasColumnName("requires_collar_option");

                    b.Property<bool?>("RequiresFillerOption")
                        .HasColumnType("bit")
                        .HasColumnName("requires_filler_option");

                    b.Property<bool?>("RequiresFootRingOption")
                        .HasColumnType("bit")
                        .HasColumnName("requires_foot_ring_option");

                    b.Property<bool?>("RequiresGaugeOption")
                        .HasColumnType("bit")
                        .HasColumnName("requires_gauge_option");

                    b.Property<int>("RequiresSerialNumbers")
                        .HasColumnType("int")
                        .HasColumnName("requires_serial_numbers");

                    b.Property<bool?>("RequiresValveTypeOption")
                        .HasColumnType("bit")
                        .HasColumnName("requires_valve_type_option");

                    b.Property<string>("SystemCode")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("system_code");

                    b.HasKey("Id")
                        .HasName("PK__items__3213E83F05A16803");

                    b.HasIndex("ItemSize");

                    b.HasIndex(new[] { "ItemNo" }, "UQ__items__5202274F1F373C3F")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "ix_items_id");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.ItemSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("PK__item_siz__3213E83F747BDD7A");

                    b.HasIndex(new[] { "Id" }, "ix_item_sizes_id");

                    b.ToTable("item_sizes", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__manufact__3213E83FFEAA6498");

                    b.HasIndex(new[] { "Name" }, "UQ__manufact__72E12F1B4F381873")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "ix_manufacturers_id");

                    b.ToTable("manufacturers", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.OrderAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("blob_path");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .IsUnicode(false)
                        .HasColumnType("varchar(260)")
                        .HasColumnName("file_name");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id")
                        .HasName("PK_order_attachments");

                    b.HasIndex(new[] { "OrderId" }, "ix_order_attachments_order_id");

                    b.ToTable("order_attachments", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.PartCrossReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErpItemNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("erp_item_number");

                    b.Property<string>("LpcItemNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lpc_item_number");

                    b.HasKey("Id")
                        .HasName("PK__part_cro__3213E83FF0BAB81B");

                    b.HasIndex(new[] { "Id" }, "ix_part_cross_references_id");

                    b.ToTable("part_cross_references", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.PaymentTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("NoOfDays")
                        .HasColumnType("int")
                        .HasColumnName("no_of_days");

                    b.Property<string>("TermsCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("terms_code");

                    b.HasKey("Id")
                        .HasName("PK__payment___3213E83F48AF8F4C");

                    b.HasIndex(new[] { "Name" }, "UQ__payment___72E12F1BF114EE48")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "ix_payment_terms_id");

                    b.ToTable("payment_terms", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Pricing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("notes");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("float")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("PK__pricings__3213E83F892AAA3D");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ItemId");

                    b.HasIndex(new[] { "Id" }, "ix_pricings_id");

                    b.ToTable("pricings", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BillToAddressId")
                        .HasColumnType("int")
                        .HasColumnName("bill_to_address_id");

                    b.Property<string>("Carrier")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("carrier");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("closed_date");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("comments");

                    b.Property<decimal?>("Commision")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("commision");

                    b.Property<string>("Contact")
                        .HasMaxLength(550)
                        .IsUnicode(false)
                        .HasColumnType("varchar(550)")
                        .HasColumnName("contact");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerPoNo")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customer_po_no");

                    b.Property<DateTime?>("DispatchDate")
                        .HasColumnType("datetime")
                        .HasColumnName("dispatch_date");

                    b.Property<DateTime?>("EmailSentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("email_sent_date");

                    b.Property<DateTime?>("EstDeliveryDate")
                        .HasColumnType("datetime")
                        .HasColumnName("est_delivery_date");

                    b.Property<decimal?>("FreightAmount")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("freight_amount");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime")
                        .HasColumnName("invoice_date");

                    b.Property<int?>("IpadOrderId")
                        .HasColumnType("int")
                        .HasColumnName("ipad_order_id");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("order_status");

                    b.Property<int?>("PaymentTermId")
                        .HasColumnType("int")
                        .HasColumnName("payment_term_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("phone");

                    b.Property<int?>("PickUpAddressId")
                        .HasColumnType("int")
                        .HasColumnName("pick_up_address_id");

                    b.Property<int?>("PickUpViaId")
                        .HasColumnType("int")
                        .HasColumnName("pick_up_via_id");

                    b.Property<DateTime?>("PickupDate")
                        .HasColumnType("datetime")
                        .HasColumnName("pickup_date");

                    b.Property<DateTime?>("PickupScheduledDate")
                        .HasColumnType("datetime")
                        .HasColumnName("pickup_scheduled_date");

                    b.Property<int?>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ReadyToShipDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ready_to_ship_date");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("received_date");

                    b.Property<int?>("ReturnBrass")
                        .HasColumnType("int")
                        .HasColumnName("return_brass");

                    b.Property<int?>("ReturnScrap")
                        .HasColumnType("int")
                        .HasColumnName("return_scrap");

                    b.Property<string>("SalesOrderNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sales_order_no");

                    b.Property<string>("SalesPersonEmpNo")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("sales_person_emp_no");

                    b.Property<int?>("SalesPersonId")
                        .HasColumnType("int")
                        .HasColumnName("sales_person_id");

                    b.Property<DateTime?>("ScheduledReceiptDate")
                        .HasColumnType("datetime")
                        .HasColumnName("scheduled_receipt_date");

                    b.Property<int?>("ShipToAddressId")
                        .HasColumnType("int")
                        .HasColumnName("ship_to_address_id");

                    b.Property<int?>("ShipToViaId")
                        .HasColumnType("int")
                        .HasColumnName("ship_to_via_id");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("site_id");

                    b.Property<string>("TrailerNo")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("trailer_no");

                    b.Property<string>("TransportationNotes")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("transportation_notes");

                    b.Property<string>("TransportationStatus")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("transportation_status");

                    b.HasKey("Id")
                        .HasName("PK__sales_or__3213E83FC96DCE65");

                    b.HasIndex("BillToAddressId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentTermId");

                    b.HasIndex("PickUpAddressId");

                    b.HasIndex("PickUpViaId");

                    b.HasIndex("SalesPersonId");

                    b.HasIndex("ShipToAddressId");

                    b.HasIndex("ShipToViaId");

                    b.HasIndex("SiteId");

                    b.HasIndex(new[] { "SalesOrderNo" }, "UQ__sales_or__ED5996F987318013")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "ix_sales_orders_id");

                    b.ToTable("sales_orders", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.SalesOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("color_id");

                    b.Property<decimal?>("Extension")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("extension");

                    b.Property<string>("Gauges")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("gauges");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemName")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("item_name");

                    b.Property<int?>("LidColorId")
                        .HasColumnType("int")
                        .HasColumnName("lid_color_id");

                    b.Property<decimal>("LineNo")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("line_no");

                    b.Property<bool?>("NeedCollars")
                        .HasColumnType("bit")
                        .HasColumnName("need_collars");

                    b.Property<bool?>("NeedDecals")
                        .HasColumnType("bit")
                        .HasColumnName("need_decals");

                    b.Property<bool?>("NeedFillers")
                        .HasColumnType("bit")
                        .HasColumnName("need_fillers");

                    b.Property<bool?>("NeedFootRings")
                        .HasColumnType("bit")
                        .HasColumnName("need_foot_rings");

                    b.Property<string>("Notes")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("notes");

                    b.Property<decimal>("QuantityAsOrdered")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("quantity_as_ordered");

                    b.Property<decimal?>("QuantityAsReceived")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("quantity_as_received");

                    b.Property<decimal?>("QuantityAsScrapped")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("quantity_as_scrapped");

                    b.Property<decimal?>("QuantityAsShipped")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("quantity_as_shipped");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int")
                        .HasColumnName("sales_order_id");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("site_id");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("unit_price");

                    b.Property<string>("ValveType")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("valve_type");

                    b.HasKey("Id")
                        .HasName("PK__sales_or__3213E83F42B18D86");

                    b.HasIndex("ColorId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LidColorId");

                    b.HasIndex("SalesOrderId");

                    b.HasIndex("SiteId");

                    b.HasIndex(new[] { "Id" }, "ix_sales_order_details_id");

                    b.ToTable("sales_order_details", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.SalesOrderDetailCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Extension")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("extension");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("quantity");

                    b.Property<int>("SalesOrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("sales_order_detail_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("PK__sales_or__3213E83F17D665A4");

                    b.HasIndex("ItemId");

                    b.HasIndex("SalesOrderDetailId");

                    b.HasIndex(new[] { "Id" }, "ix_sales_order_detail_charges_id");

                    b.ToTable("sales_order_detail_charges", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.SalesOrderDetailSn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LidColor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lid_color");

                    b.Property<string>("LidSize")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lid_size");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Mfg")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mfg");

                    b.Property<string>("MfgDate")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mfg_date");

                    b.Property<string>("MfgTestDate")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mfg_test_date");

                    b.Property<int>("SalesOrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("sales_order_detail_id");

                    b.Property<int?>("ScrapReasonId")
                        .HasColumnType("int")
                        .HasColumnName("scrap_reason_id");

                    b.Property<bool>("Scrapped")
                        .HasColumnType("bit")
                        .HasColumnName("scrapped");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__sales_or__3213E83FE1328273");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SalesOrderDetailId");

                    b.HasIndex("ScrapReasonId");

                    b.HasIndex(new[] { "Id" }, "ix_sales_order_detail_sns_id");

                    b.ToTable("sales_order_detail_sns", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.SalesPeople", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("employee_number");

                    b.Property<string>("ErpNo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("erp_no");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__sales_pe__3213E83F59F312A4");

                    b.HasIndex(new[] { "Name" }, "UQ__sales_pe__72E12F1BB2FACA05")
                        .IsUnique();

                    b.HasIndex(new[] { "EmployeeNumber" }, "UQ__sales_pe__8C453B0DBF55B5C4")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "ix_sales_peoples_id");

                    b.ToTable("sales_peoples", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.ScrapReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__scrap_re__3213E83F6E9926E7");

                    b.HasIndex(new[] { "Name" }, "UQ__scrap_re__72E12F1B20A772D7")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "ix_scrap_reasons_id");

                    b.ToTable("scrap_reasons", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.ShipVia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErpCode")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("erp_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("SystemCode")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("system_code");

                    b.HasKey("Id")
                        .HasName("PK__ship_via__3213E83F5DD7083B");

                    b.HasIndex(new[] { "Name" }, "UQ__ship_via__72E12F1B9F37D780")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "ix_ship_vias_id");

                    b.ToTable("ship_vias", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("site_code");

                    b.HasKey("Id")
                        .HasName("PK__sites__3213E83FDCF6A861");

                    b.HasIndex(new[] { "SiteCode" }, "UQ__sites__FF464BAE58768D0C")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "ix_sites_id");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Address", b =>
                {
                    b.HasOne("LPCylinderMES.Api.Models.Contact", "Contact")
                        .WithMany("Addresses")
                        .HasForeignKey("ContactId")
                        .HasConstraintName("FK__addresses__conta__46136164");

                    b.HasOne("LPCylinderMES.Api.Models.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__addresses__custo__451F3D2B");

                    b.Navigation("Contact");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Contact", b =>
                {
                    b.HasOne("LPCylinderMES.Api.Models.Customer", "Customer")
                        .WithMany("Contacts")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__contacts__custom__3E723F9C");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Customer", b =>
                {
                    b.HasOne("LPCylinderMES.Api.Models.Customer", "CustomerParent")
                        .WithMany("InverseCustomerParent")
                        .HasForeignKey("CustomerParentId")
                        .HasConstraintName("FK__customers__custo__2F2FFC0C");

                    b.HasOne("LPCylinderMES.Api.Models.Contact", "DefaultOrderContact")
                        .WithMany()
                        .HasForeignKey("DefaultOrderContactId")
                        .HasConstraintName("FK_customers_default_order_contact");

                    b.HasOne("LPCylinderMES.Api.Models.PaymentTerm", "DefaultPaymentTerm")
                        .WithMany("Customers")
                        .HasForeignKey("DefaultPaymentTermId")
                        .HasConstraintName("FK__customers__defau__30242045");

                    b.HasOne("LPCylinderMES.Api.Models.ShipVia", "DefaultShipVia")
                        .WithMany("Customers")
                        .HasForeignKey("DefaultShipViaId")
                        .HasConstraintName("FK__customers__defau__3118447E");

                    b.HasOne("LPCylinderMES.Api.Models.Color", "LidColor")
                        .WithMany("CustomerLidColors")
                        .HasForeignKey("LidColorId")
                        .HasConstraintName("FK__customers__lid_c__2E3BD7D3");

                    b.HasOne("LPCylinderMES.Api.Models.Color", "TankColor")
                        .WithMany("CustomerTankColors")
                        .HasForeignKey("TankColorId")
                        .HasConstraintName("FK__customers__tank___2D47B39A");

                    b.Navigation("CustomerParent");

                    b.Navigation("DefaultOrderContact");

                    b.Navigation("DefaultPaymentTerm");

                    b.Navigation("DefaultShipVia");

                    b.Navigation("LidColor");

                    b.Navigation("TankColor");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.CustomerItem", b =>
                {
                    b.HasOne("LPCylinderMES.Api.Models.Customer", "Customer")
                        .WithMany("CustomerItems")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__customer___custo__38B96646");

                    b.HasOne("LPCylinderMES.Api.Models.Item", "Item")
                        .WithMany("CustomerItems")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__customer___item___37C5420D");

                    b.HasOne("LPCylinderMES.Api.Models.Color", "LidColor")
                        .WithMany("CustomerItemLidColors")
                        .HasForeignKey("LidColorId")
                        .HasConstraintName("FK__customer___lid_c__3AA1AEB8");

                    b.HasOne("LPCylinderMES.Api.Models.Color", "TankColor")
                        .WithMany("CustomerItemTankColors")
                        .HasForeignKey("TankColorId")
                        .HasConstraintName("FK__customer___tank___39AD8A7F");

                    b.Navigation("Customer");

                    b.Navigation("Item");

                    b.Navigation("LidColor");

                    b.Navigation("TankColor");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Item", b =>
                {
                    b.HasOne("LPCylinderMES.Api.Models.ItemSize", "ItemSizeNavigation")
                        .WithMany("Items")
                        .HasForeignKey("ItemSize")
                        .HasConstraintName("FK__items__item_size__34E8D562");

                    b.Navigation("ItemSizeNavigation");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.OrderAttachment", b =>
                {
                    b.HasOne("LPCylinderMES.Api.Models.SalesOrder", "Order")
                        .WithMany("OrderAttachments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_order_attachments_sales_orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Pricing", b =>
                {
                    b.HasOne("LPCylinderMES.Api.Models.Customer", "Customer")
                        .WithMany("Pricings")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__pricings__custom__414EAC47");

                    b.HasOne("LPCylinderMES.Api.Models.Item", "Item")
                        .WithMany("Pricings")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__pricings__item_i__4242D080");

                    b.Navigation("Customer");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.SalesOrder", b =>
                {
                    b.HasOne("LPCylinderMES.Api.Models.Address", "BillToAddress")
                        .WithMany("SalesOrderBillToAddresses")
                        .HasForeignKey("BillToAddressId")
                        .HasConstraintName("FK__sales_ord__bill___4EA8A765");

                    b.HasOne("LPCylinderMES.Api.Models.Customer", "Customer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__sales_ord__custo__4BCC3ABA");

                    b.HasOne("LPCylinderMES.Api.Models.PaymentTerm", "PaymentTerm")
                        .WithMany("SalesOrders")
                        .HasForeignKey("PaymentTermId")
                        .HasConstraintName("FK__sales_ord__payme__51851410");

                    b.HasOne("LPCylinderMES.Api.Models.Address", "PickUpAddress")
                        .WithMany("SalesOrderPickUpAddresses")
                        .HasForeignKey("PickUpAddressId")
                        .HasConstraintName("FK__sales_ord__pick___4F9CCB9E");

                    b.HasOne("LPCylinderMES.Api.Models.ShipVia", "PickUpVia")
                        .WithMany("SalesOrderPickUpVia")
                        .HasForeignKey("PickUpViaId")
                        .HasConstraintName("FK__sales_ord__pick___4CC05EF3");

                    b.HasOne("LPCylinderMES.Api.Models.SalesPeople", "SalesPerson")
                        .WithMany("SalesOrders")
                        .HasForeignKey("SalesPersonId")
                        .HasConstraintName("FK__sales_ord__sales__49E3F248");

                    b.HasOne("LPCylinderMES.Api.Models.Address", "ShipToAddress")
                        .WithMany("SalesOrderShipToAddresses")
                        .HasForeignKey("ShipToAddressId")
                        .HasConstraintName("FK__sales_ord__ship___5090EFD7");

                    b.HasOne("LPCylinderMES.Api.Models.ShipVia", "ShipToVia")
                        .WithMany("SalesOrderShipToVia")
                        .HasForeignKey("ShipToViaId")
                        .HasConstraintName("FK__sales_ord__ship___4DB4832C");

                    b.HasOne("LPCylinderMES.Api.Models.Site", "Site")
                        .WithMany("SalesOrders")
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK__sales_ord__site___4AD81681");

                    b.Navigation("BillToAddress");

                    b.Navigation("Customer");

                    b.Navigation("PaymentTerm");

                    b.Navigation("PickUpAddress");

                    b.Navigation("PickUpVia");

                    b.Navigation("SalesPerson");

                    b.Navigation("ShipToAddress");

                    b.Navigation("ShipToVia");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.SalesOrderDetail", b =>
                {
                    b.HasOne("LPCylinderMES.Api.Models.Color", "Color")
                        .WithMany("SalesOrderDetailColors")
                        .HasForeignKey("ColorId")
                        .HasConstraintName("FK__sales_ord__color__5649C92D");

                    b.HasOne("LPCylinderMES.Api.Models.Item", "Item")
                        .WithMany("SalesOrderDetails")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__sales_ord__item___5555A4F4");

                    b.HasOne("LPCylinderMES.Api.Models.Color", "LidColor")
                        .WithMany("SalesOrderDetailLidColors")
                        .HasForeignKey("LidColorId")
                        .HasConstraintName("FK__sales_ord__lid_c__2A363CC5");

                    b.HasOne("LPCylinderMES.Api.Models.SalesOrder", "SalesOrder")
                        .WithMany("SalesOrderDetails")
                        .HasForeignKey("SalesOrderId")
                        .IsRequired()
                        .HasConstraintName("FK__sales_ord__sales__546180BB");

                    b.HasOne("LPCylinderMES.Api.Models.Site", "Site")
                        .WithMany("SalesOrderDetails")
                        .HasForeignKey("SiteId")
                        .HasConstraintName("FK__sales_ord__site___573DED66");

                    b.Navigation("Color");

                    b.Navigation("Item");

                    b.Navigation("LidColor");

                    b.Navigation("SalesOrder");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.SalesOrderDetailCharge", b =>
                {
                    b.HasOne("LPCylinderMES.Api.Models.Item", "Item")
                        .WithMany("SalesOrderDetailCharges")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__sales_ord__item___5FD33367");

                    b.HasOne("LPCylinderMES.Api.Models.SalesOrderDetail", "SalesOrderDetail")
                        .WithMany("SalesOrderDetailCharges")
                        .HasForeignKey("SalesOrderDetailId")
                        .IsRequired()
                        .HasConstraintName("FK__sales_ord__sales__5EDF0F2E");

                    b.Navigation("Item");

                    b.Navigation("SalesOrderDetail");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.SalesOrderDetailSn", b =>
                {
                    b.HasOne("LPCylinderMES.Api.Models.Manufacturer", "Manufacturer")
                        .WithMany("SalesOrderDetailSns")
                        .HasForeignKey("ManufacturerId")
                        .HasConstraintName("FK__sales_ord__manuf__5A1A5A11");

                    b.HasOne("LPCylinderMES.Api.Models.SalesOrderDetail", "SalesOrderDetail")
                        .WithMany("SalesOrderDetailSns")
                        .HasForeignKey("SalesOrderDetailId")
                        .IsRequired()
                        .HasConstraintName("FK__sales_ord__sales__5B0E7E4A");

                    b.HasOne("LPCylinderMES.Api.Models.ScrapReason", "ScrapReason")
                        .WithMany("SalesOrderDetailSns")
                        .HasForeignKey("ScrapReasonId")
                        .HasConstraintName("FK__sales_ord__scrap__5C02A283");

                    b.Navigation("Manufacturer");

                    b.Navigation("SalesOrderDetail");

                    b.Navigation("ScrapReason");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Address", b =>
                {
                    b.Navigation("SalesOrderBillToAddresses");

                    b.Navigation("SalesOrderPickUpAddresses");

                    b.Navigation("SalesOrderShipToAddresses");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Color", b =>
                {
                    b.Navigation("CustomerItemLidColors");

                    b.Navigation("CustomerItemTankColors");

                    b.Navigation("CustomerLidColors");

                    b.Navigation("CustomerTankColors");

                    b.Navigation("SalesOrderDetailColors");

                    b.Navigation("SalesOrderDetailLidColors");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Contact", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Contacts");

                    b.Navigation("CustomerItems");

                    b.Navigation("InverseCustomerParent");

                    b.Navigation("Pricings");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Item", b =>
                {
                    b.Navigation("CustomerItems");

                    b.Navigation("Pricings");

                    b.Navigation("SalesOrderDetailCharges");

                    b.Navigation("SalesOrderDetails");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.ItemSize", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Manufacturer", b =>
                {
                    b.Navigation("SalesOrderDetailSns");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.PaymentTerm", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.SalesOrder", b =>
                {
                    b.Navigation("OrderAttachments");

                    b.Navigation("SalesOrderDetails");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.SalesOrderDetail", b =>
                {
                    b.Navigation("SalesOrderDetailCharges");

                    b.Navigation("SalesOrderDetailSns");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.SalesPeople", b =>
                {
                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.ScrapReason", b =>
                {
                    b.Navigation("SalesOrderDetailSns");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.ShipVia", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("SalesOrderPickUpVia");

                    b.Navigation("SalesOrderShipToVia");
                });

            modelBuilder.Entity("LPCylinderMES.Api.Models.Site", b =>
                {
                    b.Navigation("SalesOrderDetails");

                    b.Navigation("SalesOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
