//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute("e29928a0-0e24-4501-a866-87cf7f8c49a8")]
[assembly: System.Reflection.AssemblyCompanyAttribute("LPCylinderMES.Api")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+806f898032351d116a51839c3fc92418e3d37cd8")]
[assembly: System.Reflection.AssemblyProductAttribute("LPCylinderMES.Api")]
[assembly: System.Reflection.AssemblyTitleAttribute("LPCylinderMES.Api")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

