namespace LPCylinderMES.Api.DTOs;

public record CustomerListDto(
    int Id,
    string Name,
    string? CustomerCode,
    string? Status,
    string? Email,
    string? TankColor,
    string? LidColor,
    string? BillToAddress,
    string? ShipToAddress);

public record CustomerDetailDto(
    int Id,
    string Name,
    string? CustomerCode,
    string? Status,
    string? Email,
    string? Notes,
    int? CustomerParentId,
    string? CustomerParentName,
    int? DefaultSalesEmployeeId,
    string? DefaultSalesEmployeeName,
    int? TankColorId,
    string? TankColorName,
    int? LidColorId,
    string? LidColorName,
    int? DefaultPaymentTermId,
    string? DefaultPaymentTermName,
    int? DefaultShipViaId,
    string? DefaultShipViaName,
    int? DefaultOrderContactId,
    string? DefaultOrderContactName,
    int? DefaultBillToId,
    int? DefaultPickUpId,
    int? DefaultShipToId,
    int? DefaultNeedCollars,
    int? DefaultNeedFillers,
    int? DefaultNeedFootRings,
    int? DefaultReturnScrap,
    int? DefaultReturnBrass,
    string? DefaultValveType,
    string? DefaultGauges,
    List<AddressDto> Addresses,
    List<ContactDto> Contacts);

public record CustomerCreateDto(
    string Name,
    string? CustomerCode,
    string? Status,
    string? Email);

public record CustomerUpdateDto(
    string Name,
    string? CustomerCode,
    string? Status,
    string? Email,
    string? Notes,
    int? CustomerParentId,
    int? DefaultSalesEmployeeId,
    int? TankColorId,
    int? LidColorId,
    int? DefaultPaymentTermId,
    int? DefaultShipViaId,
    int? DefaultOrderContactId,
    int? DefaultBillToId,
    int? DefaultPickUpId,
    int? DefaultShipToId,
    int? DefaultNeedCollars,
    int? DefaultNeedFillers,
    int? DefaultNeedFootRings,
    int? DefaultReturnScrap,
    int? DefaultReturnBrass,
    string? DefaultValveType,
    string? DefaultGauges);
